### ISSUE TITLE
feat: 이메일중복 , memberName 기능 구현 

### ISSUE THREAD

**Issue by kimjaeseong1** [Field-Passer/Field-Passer-BE#37]
## Description

- 이메일 중복검사 기능 구현 
-  memberName 중복검사 기능 구현
- bulid.geadle implementation 추가

## Tasks(Proccess)

- [x] bulid.geadle implementation 추가
- [x] 이메일 중복검사 기능 구현 
- [x] memberName 기능 구현

## References

- [link text](link address)
